services:
  neo4j:
    image: neo4j:5.8
    container_name: neo4j
    environment:
      NEO4J_AUTH: "neo4j/${NEO4J_PASSWORD}"
    ports:
      - "7474:7474"         # Neo4j browser
      - "7687:7687"         # Bolt
    volumes:
      - neo4j_data:/data

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env       # expose NEO4J_URI, NEO4J_PASSWORD, any other secrets
    volumes:
      - ./logs/backend:/app/logs        # Persist logs on host
      - ./.env:/app/.env:ro             # Mount .env for load_dotenv()
    environment:
      - LOG_DIR=/app/logs
    ports:
      - "8000:8000"
    depends_on:
      - neo4j

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      args:
        API_URL: "http://backend:8000"
    container_name: frontend
    volumes:
      - ./logs/frontend:/app/logs
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  neo4j_data:
