TOS = """
# Terms of Service

Welcome to **SummarAizer** (the “Service”), an AI-powered tool that helps you generate concise summaries of text, articles, and documents. These Terms of Service (“Terms”) govern your use of SummarAizer, provided by us.

By using the Service, you agree to be bound by these Terms. If you do not agree to these Terms, please do not use the Service.

---

## 1. Eligibility

You must be at least 13 years old (or the minimum age of digital consent in your jurisdiction) to use SummarAizer. By using the Service, you represent and warrant that you meet this requirement.

---

## 2. Use of the Service

You agree to use the Service only for lawful purposes and in accordance with these Terms. You are responsible for all activity that occurs under your account.

You agree not to:

- Use the Service to violate any applicable law or regulation.
- Upload or input content that is illegal, harmful, or infringes on the rights of others.
- Attempt to reverse engineer, decompile, or extract the underlying source code of the Service.

---

## 3. Intellectual Property

All content, trademarks, and software related to SummarAizer are owned by or licensed to us. You are granted a limited, non-exclusive, non-transferable license to use the Service in accordance with these Terms.

You retain all rights to the content you upload, but you grant us a license to use it solely for the purpose of providing and improving the Service.

---

## 4. Privacy

Your use of SummarAizer is also governed by our [Privacy Policy](#). By using the Service, you consent to the collection and use of your information as described in that policy.

---

## 5. Disclaimers

The Service is provided “as is” and “as available.” We do not guarantee the accuracy, completeness, or reliability of the summaries generated by SummarAizer. Use the results at your own discretion.

We disclaim all warranties, express or implied, including but not limited to merchantability, fitness for a particular purpose, and non-infringement.

---

## 6. Limitation of Liability

To the fullest extent permitted by law, we will not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service.

---

## 7. Termination

We reserve the right to suspend or terminate your access to the Service at any time, with or without notice, for conduct that we believe violates these Terms.

---

## 8. Changes to the Terms

We may update these Terms from time to time. If we make material changes, we will notify you through the Service or by other means. Continued use of the Service after changes are posted constitutes your acceptance of the new Terms.

---

## 9. Contact

If you have questions about these Terms, please contact us at `dau261104@gmail.com`.

"""